# Generated by Django 3.1.4 on 2020-12-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
