# Generated by Django 3.1.4 on 2020-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
